// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzlbxjeloadqpqshklxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bGJ4amVsb2FkcXBxc2hrbHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDgwMjQsImV4cCI6MjA3MjEyNDAyNH0.vdsdZQEURhw-EG8PAyWTKdmUeb7hyQJlreIp-jvKxBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});