// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkbfhxxllxhmpcbsoipt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrYmZoeHhsbHhobXBjYnNvaXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MDUxNDksImV4cCI6MjA5MDA4MTE0OX0.7Y6ptgGlngQ0VZCXPo-Q3WfVgDQAQf7MXvyec3vXZ14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});